export const GameActionTypes = {
  FETCH_EVENT_START: 'FETCH_EVENT_START',
  FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
  FETCH_EVENT_FAILURE: 'FETCH_EVENT_FAILURE',
  APPLY_CHOICE: 'APPLY_CHOICE',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SET_CHOICE_ERROR: 'SET_CHOICE_ERROR',
  RESOLVE_HUNTING: 'RESOLVE_HUNTING',
  RESOLVE_GATHER_WATER: 'RESOLVE_GATHER_WATER',
  FINISH_NAMING_COMPANION: 'FINISH_NAMING_COMPANION',
  LOAD_GAME: 'LOAD_GAME',
} as const; 